add wall-follow and docker instructions
iRobotEducation/create3_docs pull request #105
Opened 2022-07-06 12:39 UTC by alsora

Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>

2022-07-06 13:22 UTC, shamlian requested changes
Just a couple minor typos to fix, otherwise it looks good.

2022-07-06 13:22 UTC, shamlian commented on docs/api/wall-follow.md
> +When this behavior is requested, the robot will try to engage with nearby obstacles and, after a successfull engagement, it will start following the obstacle along the specified side until the maximu
successfullllllll

2022-07-06 13:22 UTC, shamlian commented on mkdocs.yml
> +      - Wall-Follow: api/wall-follow.md
I think it should be "Wall Follow" (no `-` -- this is an inconsistent usage)

2022-07-06 13:23 UTC, shamlian requested changes
Just a couple minor typos to fix, otherwise it looks good.

2022-07-06 14:13 UTC, shamlian approved these changes

2022-07-12 15:52 UTC, sebastianfer approved these changes

2022-07-12 21:59 UTC, justinIRBT approved these changes

2022-07-12 21:59 UTC, merged