Add documentation for pi to run multi interface cyclone file and docu…
iRobotEducation/create3_docs pull request #33
Opened 2022-03-29 21:03 UTC by justinIRBT

- Add documentation for pi to run multi interface cyclone file
- Document don't route laptop config to work with multiple interface
Hopefully default instruction flow for pi setup now takes people through the multi config setup that should yield them a ROS 2 topic list success for the multi-interface case.

2022-03-29 22:06 UTC, shamlian requested changes
Some minor changes. I would also suggest switching the footnote style on the Pi 4 page to use the footnote plugin (see electrical.md for an example) but this is not strictly necessary. Otherwise, looks good.

2022-03-29 22:06 UTC, shamlian commented on docs/setup/pi4.md
> +        **If you are using CycloneDDS (Galactic default), your Pi is running with multiple network interfaces (usb0 to talk to robot and wlan0 to talk to laptop).**
your Pi _may be_ running with

2022-03-29 22:06 UTC, shamlian commented on docs/setup/jetson.md
> +        **If you are using CycloneDDS (Galactic default) and want the Jetson to talk to the robot over USB and a laptop via wifi, you have a multiple interface situation.**
you have a multiple interface situation -> you will need to take extra steps to use multiple interfaces.

2022-03-29 22:06 UTC, shamlian commented on docs/setup/jetson.md
> +        **Note the differences in Jetson USB and Wifi interface names from the documentation.**
Wi-Fi

2022-03-29 22:06 UTC, shamlian commented on docs/setup/pi4.md
> +        **If you are using CycloneDDS (Galactic default), your Pi is running with multiple network interfaces (usb0 to talk to robot and wlan0 to talk to laptop).**
Pi -> Raspberry Pi®

2022-03-29 22:06 UTC, shamlian commented on docs/setup/pi4.md
> +        **You will need to export a path on the Pi to an xml config file that registers those interfaces in the CYCLONEDDS_URI.**
Pi ->  Raspberry Pi®

2022-03-30 00:50 UTC, shamlian approved these changes

2022-03-30 08:20 UTC, alsora commented on docs/setup/jetson.md
> +        **If you are using CycloneDDS (Galactic default) and want the Jetson to talk to the robot over USB and a laptop via Wi-Fi, you will need to take extra steps to use multiple interfaces.**
"to use multiple interfaces" --> "to setup CycloneDDS to use multiple network interfaces"

2022-03-30 08:24 UTC, alsora commented on docs/setup/jetson.md
> +        **You will need to export a path on the Jetson to an xml config file that registers those interfaces in the CYCLONEDDS_URI.**
I find this sentence a little bit confusing.
Maybe rephrase as:
"You will need to create on the Jetson a CycloneDDS XML configuration file and set the CYCLONEDDS_URI environment variable to its path"

2022-03-30 08:26 UTC, alsora commented on docs/setup/xml-config.md
> +    **If the robot is running with a Compute Board like a [Raspberry Pi®](../pi4) or an [NVIDIA® Jetson™](../jetson) connected, then the robot is using a multiple interface CycloneDDS config file to
"connected" --> "connected via usb"

2022-03-30 17:56 UTC, alsora approved these changes

2022-03-30 19:10 UTC, merged