Improve `cmd_vel` and wall-follow docs
iRobotEducation/create3_docs pull request #518
Opened 2024-01-15 19:15 UTC by alsora

This PR improves the documentation on how to move the robot and adds a disclaimer for wall-follow.
See related forum discussions: https://github.com/iRobotEducation/create3_docs/discussions/511 and https://github.com/iRobotEducation/create3_docs/discussions/516

FYI @slowrunner

2024-01-16 03:38 UTC, slowrunner reviewed
“from from now”
https://github.com/iRobotEducation/create3_docs/pull/518/commits/d9f32ae6676a9d534ac72d4c6bb7ae8b6678704b#:~:text=will%20be%20executed-,from%20from%20now,-%2C%20or%20a%20pre

2024-01-16 03:48 UTC, slowrunner reviewed
> https://github.com/iRobotEducation/create3_docs/pull/518/commits/d9f32ae6676a9d534ac72d4c6bb7ae8b6678704b#:~:text=ros2%20param%20get%20%2Fmotion_control%20wheels_stop_threshold_sec

My Create3 on H.2.4 returns
```
pi@WaLiPi5:~/wali_pi5/c3ws $ ros2 param get /motion_control wheels_stop_threshold_sec
Parameter not set

pi@WaLiPi5:~/wali_pi5/c3ws $ ros2 service call /motion_control/list_parameters rcl_interfaces/srv/ListParameters
waiting for service to become available...
requester: making request: rcl_interfaces.srv.ListParameters_Request(prefixes=[], depth=0)

response:
rcl_interfaces.srv.ListParameters_Response(result=rcl_interfaces.msg.ListParametersResult(names=['max_speed', 'min_speed', 'qos_overrides./parameter_events.publisher.depth', 'qos_overrides./parameter_events.publisher.durability', 'qos_overrides./parameter_events.publisher.history', 'qos_overrides./parameter_events.publisher.reliability', 'reflexes.REFLEX_BUMP', 'reflexes.REFLEX_CLIFF', 'reflexes.REFLEX_DOCK_AVOID', 'reflexes.REFLEX_GYRO_CAL', 'reflexes.REFLEX_PANIC', 'reflexes.REFLEX_PROXIMITY_SLOWDOWN', 'reflexes.REFLEX_STUCK', 'reflexes.REFLEX_VIRTUAL_WALL', 'reflexes.REFLEX_WHEEL_DROP', 'reflexes_enabled', 'safety_override', 'use_sim_time', 'wheel_accel_limit'], prefixes=['qos_overrides./parameter_events.publisher', 'reflexes']))
```

2024-01-16 16:20 UTC, alsora commented
Yes, you are right, the parameter is not available in the last released firmware.
I will remove that part of the docs, and add it back again with the next release (when the parameter will be available, as we already developed this feature).

2024-01-16 21:46 UTC, shamlian requested changes
I appreciate the goal of this PR; just some nits to pick before we can merge.

2024-01-16 21:46 UTC, shamlian commented on docs/api/wall-follow.md
> +If the obstacles you are trying to follow have gaps from the ground or low-hanging parts, it's required that the vertical clearance is either lower than the robot's base height (roughly 12 cm), such
typo: underneath

2024-01-16 21:46 UTC, shamlian commented on docs/api/moving-the-robot.md
This a thoughtful document and I appreciate the addition.

2024-01-16 21:46 UTC, shamlian commented on docs/api/docking.md
> +## Autonomous behaviors
👍

2024-01-16 21:46 UTC, shamlian commented on docs/api/moving-the-robot.md
> +The robot will keep executing the last received message until a new message arrives, which will be executed from from now, or a pre-fixed timeout expires without new messages being received.
The syntax on this sentence is a little confusing and I'm not sure I fully understand. Does this encapsulate what you are trying to say?

> The robot will execute the last received message on the topic until a fixed timeout period has passed or a new message is received, at which point the timer is restarted and this process begins again.

2024-01-16 21:46 UTC, shamlian commented on docs/api/moving-the-robot.md
> +The timeout is controlled by a ROS 2 parameter provided by the `/motion_control` node and named `/wheels_stop_threshold_sec`.
If these lines are going back in for the next version, maybe best to comment them out instead of deleting them outright?

2024-01-16 21:46 UTC, shamlian commented on docs/api/moving-the-robot.md
> +Note that, these raw velocity commands have lower "priority" than the other request-based approaches to move the robot (described in the next sections).
The comma is unnecessary.

2024-01-16 21:46 UTC, shamlian commented on docs/api/moving-the-robot.md
> +The corollary is that it's no use to publish `cmd_vel` messages while those are running, you should rather first wait for the behavior to finish or actively cancel it.
"it's _of_ no use"
Also, replace the `,` with a `;`.

2024-01-23 20:45 UTC, shamlian approved these changes

2024-01-23 20:51 UTC, merged